# Generated by Django 4.1.1 on 2022-10-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0002_rename_history_block_historyblock_cultureblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyblock',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historyblock',
            name='title',
        ),
        migrations.DeleteModel(
            name='CultureBlock',
        ),
        migrations.DeleteModel(
            name='HistoryBlock',
        ),
    ]
