# Generated by Django 4.1.1 on 2022-10-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0003_remove_historyblock_text_remove_historyblock_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='media/historyimgs')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postauthor', to='transl.multilanguagetext')),
                ('post_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttext', to='transl.multilanguagetextfield')),
                ('post_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttitle', to='transl.multilanguagetext')),
            ],
        ),
    ]
