# Generated by Django 4.1.1 on 2022-10-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0005_alter_history_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='cultureimgs')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postauthorculture', to='transl.multilanguagetext')),
                ('post_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttextculture', to='transl.multilanguagetextfield')),
                ('post_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttitleculture', to='transl.multilanguagetext')),
            ],
        ),
    ]
