# Generated by Django 4.1.1 on 2022-10-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0007_architect'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbourProjectDonors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img1', models.ImageField(upload_to='aboutproject')),
                ('donors_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutprojectdonors', to='transl.multilanguagetext')),
                ('project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutproject', to='transl.multilanguagetext')),
            ],
        ),
    ]
