# Generated by Django 4.1.1 on 2022-10-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0009_remove_abourprojectdonors_post_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abourprojectdonors',
            name='project_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutproject', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='post_img',
            field=models.ImageField(null=True, upload_to='architectimgs'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_img',
            field=models.ImageField(null=True, upload_to='cultureimgs'),
        ),
        migrations.AlterField(
            model_name='history',
            name='post_img',
            field=models.ImageField(null=True, upload_to='historyimgs'),
        ),
    ]
