# Generated by Django 4.1.1 on 2022-10-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0010_alter_abourprojectdonors_project_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abourprojectdonors',
            name='donors_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutprojectdonors', to='transl.multilanguagetextfield'),
        ),
    ]
