# Generated by Django 4.1.1 on 2022-10-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0011_alter_abourprojectdonors_donors_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='abourprojectdonors',
            name='support_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboutprojectsupports', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='abourprojectdonors',
            name='donors_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboutprojectdonors', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='abourprojectdonors',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboutproject', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='post_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postauthorarchitect', to='transl.multilanguagetext'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='post_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttextarchitect', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='post_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttitlearchitect', to='transl.multilanguagetext'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postauthorculture', to='transl.multilanguagetext'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttextculture', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttitleculture', to='transl.multilanguagetext'),
        ),
        migrations.AlterField(
            model_name='history',
            name='post_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postauthor', to='transl.multilanguagetext'),
        ),
        migrations.AlterField(
            model_name='history',
            name='post_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttext', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='history',
            name='post_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttitle', to='transl.multilanguagetext'),
        ),
    ]
