# Generated by Django 4.1.1 on 2022-10-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0013_rename_abourprojectdonors_aboutprojectdonors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutprojectdonors',
            name='post_img_first',
        ),
        migrations.RemoveField(
            model_name='aboutprojectdonors',
            name='post_img_second',
        ),
    ]
