# Generated by Django 4.1.1 on 2022-10-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0016_history_post_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='historyimgs'),
        ),
    ]
