# Generated by Django 4.1.1 on 2022-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0017_alter_history_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post_videos',
            field=models.FileField(null=True, upload_to='historyimgs', verbose_name=''),
        ),
    ]
