# Generated by Django 4.1.1 on 2022-10-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0018_alter_history_post_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post_videos',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
