# Generated by Django 4.1.1 on 2022-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0019_alter_history_post_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='post_videos',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='post_videos',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='post_videos',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
