# Generated by Django 4.1.1 on 2022-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0020_architect_post_videos_culture_post_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='architectimgs'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='cultureimgs'),
        ),
    ]
