# Generated by Django 4.1.1 on 2022-10-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0003_alter_multilanguagetext_text_en_and_more'),
        ('gori', '0022_alter_human_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(null=True)),
                ('seconds', models.IntegerField(null=True)),
                ('video_src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videossrc', to='transl.multilanguagetextfield')),
                ('video_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='transl.multilanguagetextfield')),
            ],
        ),
    ]
