# Generated by Django 4.1.1 on 2022-10-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0003_alter_multilanguagetext_text_en_and_more'),
        ('gori', '0023_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='post_videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architectvideo', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='culturevideo', to='transl.multilanguagetextfield'),
        ),
        migrations.AlterField(
            model_name='history',
            name='post_videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historyvideo', to='transl.multilanguagetextfield'),
        ),
    ]
