# Generated by Django 4.1.1 on 2022-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0027_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=250)),
                ('post_text', models.CharField(default='', max_length=5000)),
                ('post_videos', models.CharField(default='', max_length=500)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='historyimgs')),
            ],
        ),
    ]
