# Generated by Django 4.1.1 on 2022-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0028_historypin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypin',
            name='post_text',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
