# Generated by Django 4.1.1 on 2022-10-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0029_alter_historypin_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypin',
            name='post_videos',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pin',
            name='post',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='gori.historypin'),
        ),
    ]
