# Generated by Django 4.1.1 on 2022-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0031_rename_historypin_postforpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforpin',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='postpinimg'),
        ),
    ]
