# Generated by Django 4.1.1 on 2022-10-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0033_postforpin_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforpin',
            name='post_img_en',
            field=models.ImageField(blank=True, null=True, upload_to='postpinimg'),
        ),
        migrations.AddField(
            model_name='postforpin',
            name='post_source_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='postforpin',
            name='post_text_en',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='postforpin',
            name='post_title_en',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='postforpin',
            name='post_videos_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
