# Generated by Django 4.1.1 on 2022-10-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0035_remove_postforpin_post_img_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforpin',
            name='post_source_en',
        ),
    ]
