# Generated by Django 4.1.1 on 2022-10-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0036_remove_postforpin_post_source_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforpin',
            name='post_source_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
