# Generated by Django 4.1.1 on 2022-10-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0038_postforpin_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforpin',
            name='post_location_link',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
