# Generated by Django 4.1.1 on 2022-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0039_postforpin_post_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforpin',
            name='post_location',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postforpin',
            name='post_location_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
