# Generated by Django 4.1.1 on 2022-10-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0003_alter_multilanguagetext_text_en_and_more'),
        ('gori', '0040_alter_postforpin_post_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='post_image_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanimgdescription', to='transl.multilanguagetextfield'),
        ),
    ]
