# Generated by Django 4.1.1 on 2022-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0043_alter_human_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='post_img',
            field=models.ImageField(blank=True, default='humansimg/default.png', null=True, upload_to='architectimgs'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='post_img',
            field=models.ImageField(blank=True, default='humansimg/default.png', null=True, upload_to='cultureimgs'),
        ),
        migrations.AlterField(
            model_name='human',
            name='post_img',
            field=models.ImageField(blank=True, default='humansimg/default.png', null=True, upload_to='humansimg'),
        ),
    ]
