# Generated by Django 4.1.1 on 2022-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0044_alter_architect_post_img_alter_culture_post_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post_img',
            field=models.ImageField(blank=True, default='humansimg/default.png', null=True, upload_to='historyimgs'),
        ),
    ]
