# Generated by Django 4.1.1 on 2022-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0045_alter_history_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='post_cover_img',
            field=models.ImageField(blank=True, default='humansimg/default.png', null=True, upload_to='humanscoverimg'),
        ),
    ]
