# Generated by Django 4.1.1 on 2022-11-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gori', '0046_human_post_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='post_cover_img',
        ),
    ]
