# Generated by Django 4.1.1 on 2022-10-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0006_culture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='architectimgs')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postauthorarchitect', to='transl.multilanguagetext')),
                ('post_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttextarchitect', to='transl.multilanguagetextfield')),
                ('post_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttitlearchitect', to='transl.multilanguagetext')),
            ],
        ),
    ]
