# Generated by Django 4.1.1 on 2022-10-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0002_alter_multilanguagelongtext_slug_and_more'),
        ('gori', '0012_abourprojectdonors_support_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbourProjectDonors',
            new_name='AboutProjectDonors',
        ),
    ]
