# Generated by Django 4.1.1 on 2022-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanguagelongtext',
            name='slug',
            field=models.SlugField(blank=True, default='transl_slug', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='multilanguagetext',
            name='slug',
            field=models.SlugField(blank=True, default='transl_slug', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='multilanguagetextfield',
            name='slug',
            field=models.SlugField(blank=True, default='transl_slug', max_length=40, null=True),
        ),
    ]
